<template><div><nav class="table-of-contents"><ul><li><router-link to="#代码">代码</router-link></li><li><router-link to="#使用">使用</router-link></li><li><router-link to="#参数">参数</router-link></li></ul></nav>
<h1 id="use-outside-element-介绍" tabindex="-1"><a class="header-anchor" href="#use-outside-element-介绍"><span>use-outside-element 介绍</span></a></h1>
<p><code v-pre>use-outside-element</code> 用于检测鼠标点击是否发生在指定元素之外。它可以帮助你在用户点击元素外部时执行某些操作，例如关闭一个下拉菜单或模态框。</p>
<h2 id="代码" tabindex="-1"><a class="header-anchor" href="#代码"><span>代码</span></a></h2>
<div class="language-javascript line-numbers-mode line-numbers-mode" data-highlighter="prismjs" data-ext="js"><pre  class="shiki nord vp-code" style="background-color:#2e3440ff;color:#d8dee9ff" v-pre=" language-javascript"><code><span class="line"><span class="line"><span style="color:#81A1C1">import</span><span style="color:#ECEFF4"> {</span><span style="color:#8FBCBB"> onBeforeUnmount</span><span style="color:#ECEFF4">,</span><span style="color:#8FBCBB"> onMounted</span><span style="color:#ECEFF4">,</span><span style="color:#81A1C1"> type</span><span style="color:#8FBCBB"> Ref</span><span style="color:#ECEFF4"> }</span><span style="color:#81A1C1"> from</span><span style="color:#ECEFF4"> "</span><span style="color:#A3BE8C">vue</span><span style="color:#ECEFF4">"</span><span style="color:#81A1C1">;</span></span></span>
<span class="line"><span class="line"><span style="color:#616E88">// 点击盒子外的元素触发回调函数</span></span></span>
<span class="line"><span class="line"><span style="color:#81A1C1">const</span><span style="color:#88C0D0"> useClickOutSide</span><span style="color:#81A1C1"> =</span><span style="color:#ECEFF4"> (</span><span style="color:#D8DEE9">el</span><span style="color:#81A1C1">:</span><span style="color:#D8DEE9FF"> Ref</span><span style="color:#ECEFF4">&#x3C;</span><span style="color:#D8DEE9FF">HTMLElement </span><span style="color:#81A1C1">|</span><span style="color:#8FBCBB"> null</span><span style="color:#ECEFF4">>,</span><span style="color:#88C0D0"> callback</span><span style="color:#81A1C1">:</span><span style="color:#D8DEE9FF"> Function</span><span style="color:#ECEFF4">)</span><span style="color:#81A1C1"> =></span><span style="color:#ECEFF4"> {</span></span></span>
<span class="line"><span class="line"><span style="color:#81A1C1">  const</span><span style="color:#88C0D0"> handleClickOutside</span><span style="color:#81A1C1"> =</span><span style="color:#ECEFF4"> (</span><span style="color:#D8DEE9">e</span><span style="color:#81A1C1">:</span><span style="color:#D8DEE9FF"> MouseEvent</span><span style="color:#ECEFF4">)</span><span style="color:#81A1C1">:</span><span style="color:#81A1C1"> void</span><span style="color:#81A1C1"> =></span><span style="color:#ECEFF4"> {</span></span></span>
<span class="line"><span class="line"><span style="color:#81A1C1">    const</span><span style="color:#D8DEE9"> target</span><span style="color:#81A1C1"> =</span><span style="color:#D8DEE9"> e</span><span style="color:#ECEFF4">.</span><span style="color:#D8DEE9">target</span><span style="color:#81A1C1"> as</span><span style="color:#D8DEE9FF"> HTMLElement</span><span style="color:#81A1C1">;</span></span></span>
<span class="line"><span class="line"><span style="color:#81A1C1">    if</span><span style="color:#D8DEE9FF"> (</span><span style="color:#D8DEE9">el</span><span style="color:#ECEFF4">.</span><span style="color:#D8DEE9">value</span><span style="color:#81A1C1"> &#x26;&#x26;</span><span style="color:#D8DEE9"> target</span><span style="color:#D8DEE9FF">) </span><span style="color:#ECEFF4">{</span></span></span>
<span class="line"><span class="line"><span style="color:#81A1C1">      const</span><span style="color:#D8DEE9"> contain</span><span style="color:#81A1C1"> =</span><span style="color:#D8DEE9"> el</span><span style="color:#ECEFF4">.</span><span style="color:#D8DEE9">value</span><span style="color:#ECEFF4">.</span><span style="color:#88C0D0">contains</span><span style="color:#D8DEE9FF">(</span><span style="color:#D8DEE9">target</span><span style="color:#D8DEE9FF">)</span><span style="color:#81A1C1">;</span></span></span>
<span class="line"><span class="line"><span style="color:#81A1C1">      if</span><span style="color:#D8DEE9FF"> (</span><span style="color:#81A1C1">!</span><span style="color:#D8DEE9">contain</span><span style="color:#D8DEE9FF">) </span><span style="color:#ECEFF4">{</span></span></span>
<span class="line"><span class="line"><span style="color:#88C0D0">        callback</span><span style="color:#D8DEE9FF">()</span><span style="color:#81A1C1">;</span></span></span>
<span class="line"><span class="line"><span style="color:#ECEFF4">      }</span></span></span>
<span class="line"><span class="line"><span style="color:#ECEFF4">    }</span></span></span>
<span class="line"><span class="line"><span style="color:#ECEFF4">  }</span><span style="color:#81A1C1">;</span></span></span>
<span class="line"><span class="line"><span style="color:#88C0D0">  onMounted</span><span style="color:#D8DEE9FF">(</span><span style="color:#ECEFF4">()</span><span style="color:#81A1C1"> =></span><span style="color:#ECEFF4"> {</span></span></span>
<span class="line"><span class="line"><span style="color:#D8DEE9">    document</span><span style="color:#ECEFF4">.</span><span style="color:#88C0D0">addEventListener</span><span style="color:#D8DEE9FF">(</span><span style="color:#ECEFF4">"</span><span style="color:#A3BE8C">click</span><span style="color:#ECEFF4">"</span><span style="color:#ECEFF4">,</span><span style="color:#D8DEE9"> handleClickOutside</span><span style="color:#D8DEE9FF">)</span><span style="color:#81A1C1">;</span></span></span>
<span class="line"><span class="line"><span style="color:#ECEFF4">  }</span><span style="color:#D8DEE9FF">)</span><span style="color:#81A1C1">;</span></span></span>
<span class="line"><span class="line"><span style="color:#88C0D0">  onBeforeUnmount</span><span style="color:#D8DEE9FF">(</span><span style="color:#ECEFF4">()</span><span style="color:#81A1C1"> =></span><span style="color:#ECEFF4"> {</span></span></span>
<span class="line"><span class="line"><span style="color:#D8DEE9">    document</span><span style="color:#ECEFF4">.</span><span style="color:#88C0D0">removeEventListener</span><span style="color:#D8DEE9FF">(</span><span style="color:#ECEFF4">"</span><span style="color:#A3BE8C">click</span><span style="color:#ECEFF4">"</span><span style="color:#ECEFF4">,</span><span style="color:#D8DEE9"> handleClickOutside</span><span style="color:#D8DEE9FF">)</span><span style="color:#81A1C1">;</span></span></span>
<span class="line"><span class="line"><span style="color:#ECEFF4">  }</span><span style="color:#D8DEE9FF">)</span><span style="color:#81A1C1">;</span></span></span>
<span class="line"><span class="line"><span style="color:#ECEFF4">}</span><span style="color:#81A1C1">;</span></span></span>
<span class="line"><span class="line"><span style="color:#81A1C1">export</span><span style="color:#81A1C1"> default</span><span style="color:#ECEFF4"> {</span><span style="color:#D8DEE9">useClickOutSide</span><span style="color:#ECEFF4">}</span><span style="color:#81A1C1">;</span></span></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div><div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><h2 id="使用" tabindex="-1"><a class="header-anchor" href="#使用"><span>使用</span></a></h2>
<div class="language-javascript line-numbers-mode line-numbers-mode" data-highlighter="prismjs" data-ext="js"><pre  class="shiki nord vp-code" style="background-color:#2e3440ff;color:#d8dee9ff" v-pre=" language-javascript"><code><span class="line"><span class="line"><span style="color:#81A1C1">import</span><span style="color:#ECEFF4"> {</span><span style="color:#8FBCBB"> ref</span><span style="color:#ECEFF4"> }</span><span style="color:#81A1C1"> from</span><span style="color:#ECEFF4"> "</span><span style="color:#A3BE8C">vue</span><span style="color:#ECEFF4">"</span><span style="color:#81A1C1">;</span></span></span>
<span class="line"><span class="line"><span style="color:#81A1C1">import</span><span style="color:#ECEFF4"> {</span><span style="color:#8FBCBB"> useClickOutSide</span><span style="color:#ECEFF4"> }</span><span style="color:#81A1C1"> from</span><span style="color:#ECEFF4"> "</span><span style="color:#A3BE8C">@/hooks/use-outside-element</span><span style="color:#ECEFF4">"</span><span style="color:#81A1C1">;</span></span></span>
<span class="line"><span class="line"></span></span>
<span class="line"><span class="line"><span style="color:#81A1C1">const</span><span style="color:#D8DEE9"> el</span><span style="color:#81A1C1"> =</span><span style="color:#D8DEE9FF"> (</span><span style="color:#D8DEE9">ref</span><span style="color:#81A1C1"> &#x3C;</span><span style="color:#D8DEE9"> HTMLElement</span><span style="color:#D8DEE9FF">) </span><span style="color:#81A1C1">|</span><span style="color:#D8DEE9FF"> (</span><span style="color:#81A1C1">null</span><span style="color:#81A1C1"> ></span><span style="color:#81A1C1"> null</span><span style="color:#D8DEE9FF">)</span><span style="color:#81A1C1">;</span></span></span>
<span class="line"><span class="line"><span style="color:#81A1C1">const</span><span style="color:#88C0D0"> handleOutsideClick</span><span style="color:#81A1C1"> =</span><span style="color:#ECEFF4"> ()</span><span style="color:#81A1C1"> =></span><span style="color:#ECEFF4"> {</span></span></span>
<span class="line"><span class="line"><span style="color:#D8DEE9">  console</span><span style="color:#ECEFF4">.</span><span style="color:#88C0D0">log</span><span style="color:#D8DEE9FF">(</span><span style="color:#ECEFF4">"</span><span style="color:#A3BE8C">点击了盒子外</span><span style="color:#ECEFF4">"</span><span style="color:#D8DEE9FF">)</span><span style="color:#81A1C1">;</span></span></span>
<span class="line"><span class="line"><span style="color:#ECEFF4">}</span><span style="color:#81A1C1">;</span></span></span>
<span class="line"><span class="line"><span style="color:#88C0D0">useClickOutSide</span><span style="color:#D8DEE9FF">(</span><span style="color:#D8DEE9">el</span><span style="color:#ECEFF4">,</span><span style="color:#D8DEE9"> handleOutsideClick</span><span style="color:#D8DEE9FF">)</span><span style="color:#81A1C1">;</span></span></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div><div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><h2 id="参数" tabindex="-1"><a class="header-anchor" href="#参数"><span>参数</span></a></h2>
<ul>
<li><code v-pre>el</code>：需要检测的元素，类型为 <code v-pre>Ref&lt;HTMLElement | null&gt;</code>。</li>
<li><code v-pre>callback</code>：点击元素外部时触发的回调函数，类型为 <code v-pre>Function</code>。</li>
</ul>
</div></template>


