<template><div><h1 id="use-window-size-介绍" tabindex="-1"><a class="header-anchor" href="#use-window-size-介绍"><span>use-window-size 介绍</span></a></h1>
<p><code v-pre>use-window-size</code> 用于获取窗口的尺寸。它返回一个包含窗口宽度和高度的响应式对象。</p>
<h2 id="代码" tabindex="-1"><a class="header-anchor" href="#代码"><span>代码</span></a></h2>
<div class="language-javascript line-numbers-mode line-numbers-mode" data-highlighter="prismjs" data-ext="js"><pre  class="shiki nord vp-code" style="background-color:#2e3440ff;color:#d8dee9ff" v-pre=" language-javascript"><code><span class="line"><span class="line"><span style="color:#81A1C1">import</span><span style="color:#ECEFF4"> {</span><span style="color:#8FBCBB"> ref</span><span style="color:#ECEFF4">,</span><span style="color:#8FBCBB"> onMounted</span><span style="color:#ECEFF4">,</span><span style="color:#8FBCBB"> onUnmounted</span><span style="color:#ECEFF4"> }</span><span style="color:#81A1C1"> from</span><span style="color:#ECEFF4"> "</span><span style="color:#A3BE8C">vue</span><span style="color:#ECEFF4">"</span><span style="color:#81A1C1">;</span></span></span>
<span class="line"><span class="line"></span></span>
<span class="line"><span class="line"><span style="color:#81A1C1">function</span><span style="color:#88C0D0"> useWindowSize</span><span style="color:#ECEFF4">()</span><span style="color:#ECEFF4"> {</span></span></span>
<span class="line"><span class="line"><span style="color:#81A1C1">  const</span><span style="color:#D8DEE9"> width</span><span style="color:#81A1C1"> =</span><span style="color:#88C0D0"> ref</span><span style="color:#D8DEE9FF">(</span><span style="color:#D8DEE9">window</span><span style="color:#ECEFF4">.</span><span style="color:#D8DEE9">innerWidth</span><span style="color:#D8DEE9FF">)</span><span style="color:#81A1C1">;</span></span></span>
<span class="line"><span class="line"><span style="color:#81A1C1">  const</span><span style="color:#D8DEE9"> height</span><span style="color:#81A1C1"> =</span><span style="color:#88C0D0"> ref</span><span style="color:#D8DEE9FF">(</span><span style="color:#D8DEE9">window</span><span style="color:#ECEFF4">.</span><span style="color:#D8DEE9">innerHeight</span><span style="color:#D8DEE9FF">)</span><span style="color:#81A1C1">;</span></span></span>
<span class="line"><span class="line"><span style="color:#81A1C1">  const</span><span style="color:#88C0D0"> handleResize</span><span style="color:#81A1C1"> =</span><span style="color:#ECEFF4"> ()</span><span style="color:#81A1C1"> =></span><span style="color:#ECEFF4"> {</span></span></span>
<span class="line"><span class="line"><span style="color:#D8DEE9">    width</span><span style="color:#ECEFF4">.</span><span style="color:#D8DEE9">value</span><span style="color:#81A1C1"> =</span><span style="color:#D8DEE9"> window</span><span style="color:#ECEFF4">.</span><span style="color:#D8DEE9">innerWidth</span><span style="color:#81A1C1">;</span></span></span>
<span class="line"><span class="line"><span style="color:#D8DEE9">    height</span><span style="color:#ECEFF4">.</span><span style="color:#D8DEE9">value</span><span style="color:#81A1C1"> =</span><span style="color:#D8DEE9"> window</span><span style="color:#ECEFF4">.</span><span style="color:#D8DEE9">innerHeight</span><span style="color:#81A1C1">;</span></span></span>
<span class="line"><span class="line"><span style="color:#ECEFF4">  }</span><span style="color:#81A1C1">;</span></span></span>
<span class="line"><span class="line"><span style="color:#88C0D0">  onMounted</span><span style="color:#D8DEE9FF">(</span><span style="color:#ECEFF4">()</span><span style="color:#81A1C1"> =></span><span style="color:#ECEFF4"> {</span></span></span>
<span class="line"><span class="line"><span style="color:#D8DEE9">    window</span><span style="color:#ECEFF4">.</span><span style="color:#88C0D0">addEventListener</span><span style="color:#D8DEE9FF">(</span><span style="color:#ECEFF4">"</span><span style="color:#A3BE8C">resize</span><span style="color:#ECEFF4">"</span><span style="color:#ECEFF4">,</span><span style="color:#D8DEE9"> handleResize</span><span style="color:#D8DEE9FF">)</span><span style="color:#81A1C1">;</span></span></span>
<span class="line"><span class="line"><span style="color:#ECEFF4">  }</span><span style="color:#D8DEE9FF">)</span><span style="color:#81A1C1">;</span></span></span>
<span class="line"><span class="line"></span></span>
<span class="line"><span class="line"><span style="color:#88C0D0">  onUnmounted</span><span style="color:#D8DEE9FF">(</span><span style="color:#ECEFF4">()</span><span style="color:#81A1C1"> =></span><span style="color:#ECEFF4"> {</span></span></span>
<span class="line"><span class="line"><span style="color:#D8DEE9">    window</span><span style="color:#ECEFF4">.</span><span style="color:#88C0D0">removeEventListener</span><span style="color:#D8DEE9FF">(</span><span style="color:#ECEFF4">"</span><span style="color:#A3BE8C">resize</span><span style="color:#ECEFF4">"</span><span style="color:#ECEFF4">,</span><span style="color:#D8DEE9"> handleResize</span><span style="color:#D8DEE9FF">)</span><span style="color:#81A1C1">;</span></span></span>
<span class="line"><span class="line"><span style="color:#ECEFF4">  }</span><span style="color:#D8DEE9FF">)</span><span style="color:#81A1C1">;</span></span></span>
<span class="line"><span class="line"></span></span>
<span class="line"><span class="line"><span style="color:#81A1C1">  return</span><span style="color:#ECEFF4"> {</span><span style="color:#D8DEE9"> width</span><span style="color:#ECEFF4">,</span><span style="color:#D8DEE9"> height</span><span style="color:#ECEFF4"> }</span><span style="color:#81A1C1">;</span></span></span>
<span class="line"><span class="line"><span style="color:#ECEFF4">}</span></span></span>
<span class="line"><span class="line"><span style="color:#81A1C1">export</span><span style="color:#ECEFF4"> {</span><span style="color:#8FBCBB"> useWindowSize</span><span style="color:#ECEFF4"> }</span><span style="color:#81A1C1">;</span></span></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div><div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><h2 id="使用" tabindex="-1"><a class="header-anchor" href="#使用"><span>使用</span></a></h2>
<div class="language-javascript line-numbers-mode line-numbers-mode" data-highlighter="prismjs" data-ext="js"><pre  class="shiki nord vp-code" style="background-color:#2e3440ff;color:#d8dee9ff" v-pre=" language-javascript"><code><span class="line"><span class="line"><span style="color:#81A1C1">import</span><span style="color:#ECEFF4"> {</span><span style="color:#8FBCBB"> useWindowSize</span><span style="color:#ECEFF4"> }</span><span style="color:#81A1C1"> from</span><span style="color:#ECEFF4"> "</span><span style="color:#A3BE8C">@/hooks/use-window-size</span><span style="color:#ECEFF4">"</span><span style="color:#81A1C1">;</span></span></span>
<span class="line"><span class="line"><span style="color:#81A1C1">export</span><span style="color:#81A1C1"> default</span><span style="color:#ECEFF4"> {</span></span></span>
<span class="line"><span class="line"><span style="color:#88C0D0">  setup</span><span style="color:#ECEFF4">()</span><span style="color:#ECEFF4"> {</span></span></span>
<span class="line"><span class="line"><span style="color:#81A1C1">    const</span><span style="color:#ECEFF4"> {</span><span style="color:#D8DEE9"> width</span><span style="color:#ECEFF4">,</span><span style="color:#D8DEE9"> height</span><span style="color:#ECEFF4"> }</span><span style="color:#81A1C1"> =</span><span style="color:#88C0D0"> useWindowSize</span><span style="color:#D8DEE9FF">()</span><span style="color:#81A1C1">;</span></span></span>
<span class="line"><span class="line"><span style="color:#81A1C1">    return</span><span style="color:#ECEFF4"> {</span><span style="color:#D8DEE9"> width</span><span style="color:#ECEFF4">,</span><span style="color:#D8DEE9"> height</span><span style="color:#ECEFF4"> }</span><span style="color:#81A1C1">;</span></span></span>
<span class="line"><span class="line"><span style="color:#ECEFF4">  },</span></span></span>
<span class="line"><span class="line"><span style="color:#ECEFF4">}</span><span style="color:#81A1C1">;</span></span></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div><div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><h2 id="示例" tabindex="-1"><a class="header-anchor" href="#示例"><span>示例</span></a></h2>
<div class="language-html line-numbers-mode line-numbers-mode" data-highlighter="prismjs" data-ext="html"><pre  class="shiki nord vp-code" style="background-color:#2e3440ff;color:#d8dee9ff" v-pre=" language-html"><code><span class="line"><span class="line"><span style="color:#81A1C1">&#x3C;template></span></span></span>
<span class="line"><span class="line"><span style="color:#81A1C1">  &#x3C;div></span></span></span>
<span class="line"><span class="line"><span style="color:#81A1C1">    &#x3C;p></span><span style="color:#D8DEE9FF">窗口宽度: {{ width }}</span><span style="color:#81A1C1">&#x3C;/p></span></span></span>
<span class="line"><span class="line"><span style="color:#81A1C1">    &#x3C;p></span><span style="color:#D8DEE9FF">窗口高度: {{ height }}</span><span style="color:#81A1C1">&#x3C;/p></span></span></span>
<span class="line"><span class="line"><span style="color:#81A1C1">  &#x3C;/div></span></span></span>
<span class="line"><span class="line"><span style="color:#81A1C1">&#x3C;/template></span></span></span>
<span class="line"><span class="line"></span></span>
<span class="line"><span class="line"><span style="color:#81A1C1">&#x3C;script></span></span></span>
<span class="line"><span class="line"><span style="color:#81A1C1">import</span><span style="color:#8FBCBB"> useWindowSize</span><span style="color:#81A1C1"> from</span><span style="color:#ECEFF4"> "</span><span style="color:#A3BE8C">./use-window-size</span><span style="color:#ECEFF4">"</span><span style="color:#81A1C1">;</span></span></span>
<span class="line"><span class="line"></span></span>
<span class="line"><span class="line"><span style="color:#81A1C1">export</span><span style="color:#81A1C1"> default</span><span style="color:#ECEFF4"> {</span></span></span>
<span class="line"><span class="line"><span style="color:#88C0D0">  setup</span><span style="color:#ECEFF4">()</span><span style="color:#ECEFF4"> {</span></span></span>
<span class="line"><span class="line"><span style="color:#81A1C1">    const</span><span style="color:#ECEFF4"> {</span><span style="color:#D8DEE9"> width</span><span style="color:#ECEFF4">,</span><span style="color:#D8DEE9"> height</span><span style="color:#ECEFF4"> }</span><span style="color:#81A1C1"> =</span><span style="color:#88C0D0"> useWindowSize</span><span style="color:#D8DEE9FF">()</span><span style="color:#81A1C1">;</span></span></span>
<span class="line"><span class="line"><span style="color:#81A1C1">    return</span><span style="color:#ECEFF4"> {</span><span style="color:#D8DEE9"> width</span><span style="color:#ECEFF4">,</span><span style="color:#D8DEE9"> height</span><span style="color:#ECEFF4"> }</span><span style="color:#81A1C1">;</span></span></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div><div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div></div></template>


