<template><div><h1 id="use-zindex-介绍" tabindex="-1"><a class="header-anchor" href="#use-zindex-介绍"><span>use-zindex 介绍</span></a></h1>
<p><code v-pre>use-zindex</code>用于管理 z-index 值。它提供了一种简单的方式来获取和设置 z-index 值，确保组件之间的层级关系不会发生冲突。</p>
<h2 id="代码" tabindex="-1"><a class="header-anchor" href="#代码"><span>代码</span></a></h2>
<div class="language-javascript line-numbers-mode line-numbers-mode" data-highlighter="prismjs" data-ext="js"><pre  class="shiki nord vp-code" style="background-color:#2e3440ff;color:#d8dee9ff" v-pre=" language-javascript"><code><span class="line"><span class="line"><span style="color:#81A1C1">import</span><span style="color:#ECEFF4"> {</span><span style="color:#8FBCBB"> computed</span><span style="color:#ECEFF4">,</span><span style="color:#8FBCBB"> ref</span><span style="color:#ECEFF4"> }</span><span style="color:#81A1C1"> from</span><span style="color:#ECEFF4"> "</span><span style="color:#A3BE8C">vue</span><span style="color:#ECEFF4">"</span><span style="color:#81A1C1">;</span></span></span>
<span class="line"><span class="line"><span style="color:#81A1C1">let</span><span style="color:#D8DEE9"> seed</span><span style="color:#81A1C1"> =</span><span style="color:#88C0D0"> ref</span><span style="color:#D8DEE9FF">(</span><span style="color:#B48EAD">0</span><span style="color:#D8DEE9FF">)</span><span style="color:#81A1C1">;</span></span></span>
<span class="line"><span class="line"><span style="color:#81A1C1">export</span><span style="color:#81A1C1"> const</span><span style="color:#88C0D0"> useZIndex</span><span style="color:#81A1C1"> =</span><span style="color:#ECEFF4"> (</span><span style="color:#D8DEE9">zIndex</span><span style="color:#81A1C1"> =</span><span style="color:#B48EAD"> 1000</span><span style="color:#ECEFF4">)</span><span style="color:#81A1C1"> =></span><span style="color:#ECEFF4"> {</span></span></span>
<span class="line"><span class="line"><span style="color:#81A1C1">  const</span><span style="color:#D8DEE9"> initZIndex</span><span style="color:#81A1C1"> =</span><span style="color:#88C0D0"> ref</span><span style="color:#D8DEE9FF">(</span><span style="color:#D8DEE9">zIndex</span><span style="color:#D8DEE9FF">)</span><span style="color:#81A1C1">;</span></span></span>
<span class="line"><span class="line"><span style="color:#81A1C1">  const</span><span style="color:#D8DEE9"> currentZIndex</span><span style="color:#81A1C1"> =</span><span style="color:#88C0D0"> computed</span><span style="color:#D8DEE9FF">(</span><span style="color:#ECEFF4">()</span><span style="color:#81A1C1"> =></span><span style="color:#D8DEE9"> seed</span><span style="color:#ECEFF4">.</span><span style="color:#D8DEE9">value</span><span style="color:#81A1C1"> +</span><span style="color:#D8DEE9"> initZIndex</span><span style="color:#ECEFF4">.</span><span style="color:#D8DEE9">value</span><span style="color:#D8DEE9FF">)</span><span style="color:#81A1C1">;</span></span></span>
<span class="line"><span class="line"><span style="color:#81A1C1">  const</span><span style="color:#88C0D0"> nextZIndex</span><span style="color:#81A1C1"> =</span><span style="color:#ECEFF4"> ()</span><span style="color:#81A1C1"> =></span><span style="color:#ECEFF4"> {</span></span></span>
<span class="line"><span class="line"><span style="color:#D8DEE9">    seed</span><span style="color:#ECEFF4">.</span><span style="color:#D8DEE9">value</span><span style="color:#81A1C1">++;</span></span></span>
<span class="line"><span class="line"><span style="color:#81A1C1">    return</span><span style="color:#D8DEE9"> currentZIndex</span><span style="color:#ECEFF4">.</span><span style="color:#D8DEE9">value</span><span style="color:#81A1C1">;</span></span></span>
<span class="line"><span class="line"><span style="color:#ECEFF4">  }</span><span style="color:#81A1C1">;</span></span></span>
<span class="line"><span class="line"><span style="color:#81A1C1">  return</span><span style="color:#ECEFF4"> {</span></span></span>
<span class="line"><span class="line"><span style="color:#D8DEE9">    initZIndex</span><span style="color:#ECEFF4">,</span></span></span>
<span class="line"><span class="line"><span style="color:#D8DEE9">    currentZIndex</span><span style="color:#ECEFF4">,</span></span></span>
<span class="line"><span class="line"><span style="color:#D8DEE9">    nextZIndex</span><span style="color:#ECEFF4">,</span></span></span>
<span class="line"><span class="line"><span style="color:#ECEFF4">  }</span><span style="color:#81A1C1">;</span></span></span>
<span class="line"><span class="line"><span style="color:#ECEFF4">}</span><span style="color:#81A1C1">;</span></span></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div><div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><h2 id="用法" tabindex="-1"><a class="header-anchor" href="#用法"><span>用法</span></a></h2>
<div class="language-javascript line-numbers-mode line-numbers-mode" data-highlighter="prismjs" data-ext="js"><pre  class="shiki nord vp-code" style="background-color:#2e3440ff;color:#d8dee9ff" v-pre=" language-javascript"><code><span class="line"><span class="line"><span style="color:#81A1C1">import</span><span style="color:#ECEFF4"> {</span><span style="color:#8FBCBB"> useZIndex</span><span style="color:#ECEFF4"> }</span><span style="color:#81A1C1"> from</span><span style="color:#ECEFF4"> "</span><span style="color:#A3BE8C">@/hooks/use-zindex</span><span style="color:#ECEFF4">"</span><span style="color:#81A1C1">;</span></span></span>
<span class="line"><span class="line"></span></span>
<span class="line"><span class="line"><span style="color:#81A1C1">export</span><span style="color:#81A1C1"> default</span><span style="color:#ECEFF4"> {</span></span></span>
<span class="line"><span class="line"><span style="color:#88C0D0">  setup</span><span style="color:#ECEFF4">()</span><span style="color:#ECEFF4"> {</span></span></span>
<span class="line"><span class="line"><span style="color:#81A1C1">    const</span><span style="color:#ECEFF4"> {</span><span style="color:#D8DEE9"> currentZIndex</span><span style="color:#ECEFF4">,</span><span style="color:#D8DEE9"> nextZIndex</span><span style="color:#ECEFF4"> }</span><span style="color:#81A1C1"> =</span><span style="color:#88C0D0"> useZIndex</span><span style="color:#D8DEE9FF">(</span><span style="color:#B48EAD">1000</span><span style="color:#D8DEE9FF">)</span><span style="color:#81A1C1">;</span></span></span>
<span class="line"><span class="line"><span style="color:#81A1C1">    return</span><span style="color:#ECEFF4"> {</span></span></span>
<span class="line"><span class="line"><span style="color:#D8DEE9">      currentZIndex</span><span style="color:#ECEFF4">,</span></span></span>
<span class="line"><span class="line"><span style="color:#D8DEE9">      nextZIndex</span><span style="color:#ECEFF4">,</span></span></span>
<span class="line"><span class="line"><span style="color:#ECEFF4">    }</span><span style="color:#81A1C1">;</span></span></span>
<span class="line"><span class="line"><span style="color:#ECEFF4">  },</span></span></span>
<span class="line"><span class="line"><span style="color:#ECEFF4">}</span><span style="color:#81A1C1">;</span></span></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div><div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><h2 id="参数" tabindex="-1"><a class="header-anchor" href="#参数"><span>参数</span></a></h2>
<ul>
<li><code v-pre>zIndex</code>：初始 z-index 值，默认为 1000。</li>
</ul>
<h2 id="返回值" tabindex="-1"><a class="header-anchor" href="#返回值"><span>返回值</span></a></h2>
<ul>
<li><code v-pre>initZIndex</code>：初始 z-index 值。</li>
<li><code v-pre>currentZIndex</code>：当前 z-index 值。</li>
<li><code v-pre>nextZIndex</code>：获取下一个 z-index 值的函数。</li>
</ul>
<h2 id="示例" tabindex="-1"><a class="header-anchor" href="#示例"><span>示例</span></a></h2>
<div class="language-vue line-numbers-mode line-numbers-mode" data-highlighter="prismjs" data-ext="vue"><pre  class="shiki nord vp-code" style="background-color:#2e3440ff;color:#d8dee9ff" v-pre=" language-vue"><code><span class="line"><span class="line"><span style="color:#81A1C1">&#x3C;template></span></span></span>
<span class="line"><span class="line"><span style="color:#81A1C1">  &#x3C;div</span><span style="color:#ECEFF4"> :</span><span style="color:#8FBCBB">style</span><span style="color:#ECEFF4">=</span><span style="color:#ECEFF4">"</span><span style="color:#ECEFF4">{</span><span style="color:#D8DEE9"> zIndex</span><span style="color:#ECEFF4">:</span><span style="color:#D8DEE9"> currentZIndex</span><span style="color:#ECEFF4"> }</span><span style="color:#ECEFF4">"</span><span style="color:#81A1C1">></span><span style="color:#D8DEE9FF">Hello World</span><span style="color:#81A1C1">&#x3C;/div></span></span></span>
<span class="line"><span class="line"><span style="color:#81A1C1">  &#x3C;button</span><span style="color:#ECEFF4"> @</span><span style="color:#8FBCBB">click</span><span style="color:#ECEFF4">=</span><span style="color:#ECEFF4">"</span><span style="color:#D8DEE9">nextZIndex</span><span style="color:#ECEFF4">"</span><span style="color:#81A1C1">></span><span style="color:#D8DEE9FF">Next Z-Index</span><span style="color:#81A1C1">&#x3C;/button></span></span></span>
<span class="line"><span class="line"><span style="color:#81A1C1">&#x3C;/template></span></span></span>
<span class="line"><span class="line"></span></span>
<span class="line"><span class="line"><span style="color:#81A1C1">&#x3C;script></span></span></span>
<span class="line"><span class="line"><span style="color:#81A1C1">import</span><span style="color:#ECEFF4"> {</span><span style="color:#8FBCBB"> useZIndex</span><span style="color:#ECEFF4"> }</span><span style="color:#81A1C1"> from</span><span style="color:#ECEFF4"> "</span><span style="color:#A3BE8C">@/hooks/use-zindex</span><span style="color:#ECEFF4">"</span><span style="color:#81A1C1">;</span></span></span>
<span class="line"><span class="line"><span style="color:#81A1C1">export</span><span style="color:#81A1C1"> default</span><span style="color:#ECEFF4"> {</span></span></span>
<span class="line"><span class="line"><span style="color:#88C0D0">  setup</span><span style="color:#ECEFF4">()</span><span style="color:#ECEFF4"> {</span></span></span>
<span class="line"><span class="line"><span style="color:#81A1C1">    const</span><span style="color:#ECEFF4"> {</span><span style="color:#D8DEE9"> currentZIndex</span><span style="color:#ECEFF4">,</span><span style="color:#D8DEE9"> nextZIndex</span><span style="color:#ECEFF4"> }</span><span style="color:#81A1C1"> =</span><span style="color:#88C0D0"> useZIndex</span><span style="color:#D8DEE9FF">(</span><span style="color:#B48EAD">1000</span><span style="color:#D8DEE9FF">)</span><span style="color:#81A1C1">;</span></span></span>
<span class="line"><span class="line"><span style="color:#81A1C1">    return</span><span style="color:#ECEFF4"> {</span></span></span>
<span class="line"><span class="line"><span style="color:#D8DEE9">      currentZIndex</span><span style="color:#ECEFF4">,</span></span></span>
<span class="line"><span class="line"><span style="color:#D8DEE9">      nextZIndex</span><span style="color:#ECEFF4">,</span></span></span>
<span class="line"><span class="line"><span style="color:#ECEFF4">    }</span><span style="color:#81A1C1">;</span></span></span>
<span class="line"><span class="line"><span style="color:#ECEFF4">  },</span></span></span>
<span class="line"><span class="line"><span style="color:#ECEFF4">}</span><span style="color:#81A1C1">;</span></span></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div><div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div></div></template>


