<template><div><h1 id="crypto-介绍" tabindex="-1"><a class="header-anchor" href="#crypto-介绍"><span>crypto 介绍</span></a></h1>
<p><code v-pre>crypto</code> 加密解密</p>
<h2 id="安装" tabindex="-1"><a class="header-anchor" href="#安装"><span>安装</span></a></h2>
<div class="language-bash line-numbers-mode line-numbers-mode" data-highlighter="prismjs" data-ext="sh"><pre  class="shiki nord vp-code" style="background-color:#2e3440ff;color:#d8dee9ff" v-pre=" language-bash"><code><span class="line"><span class="line"><span style="color:#88C0D0">npm</span><span style="color:#A3BE8C"> install</span><span style="color:#A3BE8C"> crypto-js</span></span></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"></div><div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div></div></div><h2 id="代码" tabindex="-1"><a class="header-anchor" href="#代码"><span>代码</span></a></h2>
<div class="language-javascript line-numbers-mode line-numbers-mode" data-highlighter="prismjs" data-ext="js"><pre  class="shiki nord vp-code" style="background-color:#2e3440ff;color:#d8dee9ff" v-pre=" language-javascript"><code><span class="line"><span class="line"><span style="color:#81A1C1">import</span><span style="color:#8FBCBB"> CryptoJS</span><span style="color:#81A1C1"> from</span><span style="color:#ECEFF4"> "</span><span style="color:#A3BE8C">crypto-js</span><span style="color:#ECEFF4">"</span><span style="color:#81A1C1">;</span></span></span>
<span class="line"><span class="line"></span></span>
<span class="line"><span class="line"><span style="color:#616E88">// 密钥</span></span></span>
<span class="line"><span class="line"><span style="color:#81A1C1">const</span><span style="color:#D8DEE9"> keyStr</span><span style="color:#81A1C1"> =</span><span style="color:#ECEFF4"> "</span><span style="color:#A3BE8C">miyao==</span><span style="color:#ECEFF4">"</span><span style="color:#81A1C1">;</span></span></span>
<span class="line"><span class="line"></span></span>
<span class="line"><span class="line"><span style="color:#616E88">//加密</span></span></span>
<span class="line"><span class="line"><span style="color:#81A1C1">export</span><span style="color:#81A1C1"> function</span><span style="color:#88C0D0"> encrypt</span><span style="color:#ECEFF4">(</span><span style="color:#D8DEE9">word</span><span style="color:#ECEFF4">)</span><span style="color:#ECEFF4"> {</span></span></span>
<span class="line"><span class="line"><span style="color:#81A1C1">  const</span><span style="color:#D8DEE9"> key</span><span style="color:#81A1C1"> =</span><span style="color:#D8DEE9"> CryptoJS</span><span style="color:#ECEFF4">.</span><span style="color:#D8DEE9">enc</span><span style="color:#ECEFF4">.</span><span style="color:#D8DEE9">Utf8</span><span style="color:#ECEFF4">.</span><span style="color:#88C0D0">parse</span><span style="color:#D8DEE9FF">(</span><span style="color:#D8DEE9">keyStr</span><span style="color:#D8DEE9FF">)</span><span style="color:#81A1C1">;</span></span></span>
<span class="line"><span class="line"><span style="color:#81A1C1">  const</span><span style="color:#D8DEE9"> srcs</span><span style="color:#81A1C1"> =</span><span style="color:#D8DEE9"> CryptoJS</span><span style="color:#ECEFF4">.</span><span style="color:#D8DEE9">enc</span><span style="color:#ECEFF4">.</span><span style="color:#D8DEE9">Utf8</span><span style="color:#ECEFF4">.</span><span style="color:#88C0D0">parse</span><span style="color:#D8DEE9FF">(</span><span style="color:#D8DEE9">word</span><span style="color:#D8DEE9FF">)</span><span style="color:#81A1C1">;</span></span></span>
<span class="line"><span class="line"><span style="color:#81A1C1">  const</span><span style="color:#D8DEE9"> encrypted</span><span style="color:#81A1C1"> =</span><span style="color:#D8DEE9"> CryptoJS</span><span style="color:#ECEFF4">.</span><span style="color:#D8DEE9">AES</span><span style="color:#ECEFF4">.</span><span style="color:#88C0D0">encrypt</span><span style="color:#D8DEE9FF">(</span><span style="color:#D8DEE9">srcs</span><span style="color:#ECEFF4">,</span><span style="color:#D8DEE9"> key</span><span style="color:#ECEFF4">,</span><span style="color:#ECEFF4"> {</span></span></span>
<span class="line"><span class="line"><span style="color:#88C0D0">    mode</span><span style="color:#ECEFF4">:</span><span style="color:#D8DEE9"> CryptoJS</span><span style="color:#ECEFF4">.</span><span style="color:#D8DEE9">mode</span><span style="color:#ECEFF4">.</span><span style="color:#D8DEE9">ECB</span><span style="color:#ECEFF4">,</span></span></span>
<span class="line"><span class="line"><span style="color:#88C0D0">    padding</span><span style="color:#ECEFF4">:</span><span style="color:#D8DEE9"> CryptoJS</span><span style="color:#ECEFF4">.</span><span style="color:#D8DEE9">pad</span><span style="color:#ECEFF4">.</span><span style="color:#D8DEE9">Pkcs7</span><span style="color:#ECEFF4">,</span></span></span>
<span class="line"><span class="line"><span style="color:#ECEFF4">  }</span><span style="color:#D8DEE9FF">)</span><span style="color:#81A1C1">;</span></span></span>
<span class="line"><span class="line"><span style="color:#81A1C1">  return</span><span style="color:#D8DEE9"> encrypted</span><span style="color:#ECEFF4">.</span><span style="color:#88C0D0">toString</span><span style="color:#D8DEE9FF">()</span><span style="color:#81A1C1">;</span></span></span>
<span class="line"><span class="line"><span style="color:#ECEFF4">}</span></span></span>
<span class="line"><span class="line"></span></span>
<span class="line"><span class="line"><span style="color:#616E88">//解密</span></span></span>
<span class="line"><span class="line"><span style="color:#81A1C1">export</span><span style="color:#81A1C1"> function</span><span style="color:#88C0D0"> decrypt</span><span style="color:#ECEFF4">(</span><span style="color:#D8DEE9">word</span><span style="color:#ECEFF4">)</span><span style="color:#ECEFF4"> {</span></span></span>
<span class="line"><span class="line"><span style="color:#D8DEE9">  keyStr</span><span style="color:#81A1C1"> =</span><span style="color:#D8DEE9"> keyStr</span><span style="color:#81A1C1">;</span></span></span>
<span class="line"><span class="line"><span style="color:#81A1C1">  const</span><span style="color:#D8DEE9"> key</span><span style="color:#81A1C1"> =</span><span style="color:#D8DEE9"> CryptoJS</span><span style="color:#ECEFF4">.</span><span style="color:#D8DEE9">enc</span><span style="color:#ECEFF4">.</span><span style="color:#D8DEE9">Utf8</span><span style="color:#ECEFF4">.</span><span style="color:#88C0D0">parse</span><span style="color:#D8DEE9FF">(</span><span style="color:#D8DEE9">keyStr</span><span style="color:#D8DEE9FF">)</span><span style="color:#81A1C1">;</span></span></span>
<span class="line"><span class="line"><span style="color:#81A1C1">  const</span><span style="color:#D8DEE9"> decrypt</span><span style="color:#81A1C1"> =</span><span style="color:#D8DEE9"> CryptoJS</span><span style="color:#ECEFF4">.</span><span style="color:#D8DEE9">AES</span><span style="color:#ECEFF4">.</span><span style="color:#88C0D0">decrypt</span><span style="color:#D8DEE9FF">(</span><span style="color:#D8DEE9">word</span><span style="color:#ECEFF4">,</span><span style="color:#D8DEE9"> key</span><span style="color:#ECEFF4">,</span><span style="color:#ECEFF4"> {</span></span></span>
<span class="line"><span class="line"><span style="color:#88C0D0">    mode</span><span style="color:#ECEFF4">:</span><span style="color:#D8DEE9"> CryptoJS</span><span style="color:#ECEFF4">.</span><span style="color:#D8DEE9">mode</span><span style="color:#ECEFF4">.</span><span style="color:#D8DEE9">ECB</span><span style="color:#ECEFF4">,</span></span></span>
<span class="line"><span class="line"><span style="color:#88C0D0">    padding</span><span style="color:#ECEFF4">:</span><span style="color:#D8DEE9"> CryptoJS</span><span style="color:#ECEFF4">.</span><span style="color:#D8DEE9">pad</span><span style="color:#ECEFF4">.</span><span style="color:#D8DEE9">Pkcs7</span><span style="color:#ECEFF4">,</span></span></span>
<span class="line"><span class="line"><span style="color:#ECEFF4">  }</span><span style="color:#D8DEE9FF">)</span><span style="color:#81A1C1">;</span></span></span>
<span class="line"><span class="line"><span style="color:#81A1C1">  return</span><span style="color:#D8DEE9"> CryptoJS</span><span style="color:#ECEFF4">.</span><span style="color:#D8DEE9">enc</span><span style="color:#ECEFF4">.</span><span style="color:#D8DEE9">Utf8</span><span style="color:#ECEFF4">.</span><span style="color:#88C0D0">stringify</span><span style="color:#D8DEE9FF">(</span><span style="color:#D8DEE9">decrypt</span><span style="color:#D8DEE9FF">)</span><span style="color:#ECEFF4">.</span><span style="color:#88C0D0">toString</span><span style="color:#D8DEE9FF">()</span><span style="color:#81A1C1">;</span></span></span>
<span class="line"><span class="line"><span style="color:#ECEFF4">}</span></span></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div><div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><h2 id="使用" tabindex="-1"><a class="header-anchor" href="#使用"><span>使用</span></a></h2>
<div class="language-javascript line-numbers-mode line-numbers-mode" data-highlighter="prismjs" data-ext="js"><pre  class="shiki nord vp-code" style="background-color:#2e3440ff;color:#d8dee9ff" v-pre=" language-javascript"><code><span class="line"><span class="line"><span style="color:#81A1C1">import</span><span style="color:#ECEFF4"> {</span><span style="color:#8FBCBB"> encrypt</span><span style="color:#ECEFF4">,</span><span style="color:#8FBCBB"> decrypt</span><span style="color:#ECEFF4"> }</span><span style="color:#81A1C1"> from</span><span style="color:#ECEFF4"> "</span><span style="color:#A3BE8C">@/utils/encrypt</span><span style="color:#ECEFF4">"</span><span style="color:#81A1C1">;</span></span></span>
<span class="line"><span class="line"></span></span>
<span class="line"><span class="line"><span style="color:#616E88">// 加密</span></span></span>
<span class="line"><span class="line"><span style="color:#81A1C1">const</span><span style="color:#D8DEE9"> str</span><span style="color:#81A1C1"> =</span><span style="color:#88C0D0"> encrypt</span><span style="color:#D8DEE9FF">(</span><span style="color:#ECEFF4">"</span><span style="color:#A3BE8C">123456</span><span style="color:#ECEFF4">"</span><span style="color:#D8DEE9FF">)</span><span style="color:#81A1C1">;</span></span></span>
<span class="line"><span class="line"><span style="color:#D8DEE9">console</span><span style="color:#ECEFF4">.</span><span style="color:#88C0D0">log</span><span style="color:#D8DEE9FF">(</span><span style="color:#D8DEE9">str</span><span style="color:#D8DEE9FF">)</span><span style="color:#81A1C1">;</span></span></span>
<span class="line"><span class="line"></span></span>
<span class="line"><span class="line"><span style="color:#616E88">// 解密</span></span></span>
<span class="line"><span class="line"><span style="color:#81A1C1">const</span><span style="color:#D8DEE9"> str2</span><span style="color:#81A1C1"> =</span><span style="color:#88C0D0"> decrypt</span><span style="color:#D8DEE9FF">(</span><span style="color:#D8DEE9">str</span><span style="color:#D8DEE9FF">)</span><span style="color:#81A1C1">;</span></span></span>
<span class="line"><span class="line"><span style="color:#D8DEE9">console</span><span style="color:#ECEFF4">.</span><span style="color:#88C0D0">log</span><span style="color:#D8DEE9FF">(</span><span style="color:#D8DEE9">str2</span><span style="color:#D8DEE9FF">)</span><span style="color:#81A1C1">;</span></span></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div><div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div></div></template>


